// Auto-generated by VibeStack — deterministic assembly from PageFeatureSpec
import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog'
import { Skeleton } from '@/components/ui/skeleton'
import { Input } from '@/components/ui/input'

export const Route = createFileRoute('/_authenticated/job-tech-tags')({
  component: JobTechTagListPage,
})

function JobTechTagListPage() {
  const [sortBy, setSortBy] = useState('created_at')
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('desc')
  const [page, setPage] = useState(0)
  const pageSize = 20
  const queryClient = useQueryClient()

  const jobTechTags = useQuery({
    queryKey: ['job_tech_tags', 'list', page, sortBy, sortOrder],
    queryFn: async () => {
      const from = page * pageSize
      const to = from + pageSize - 1
      const { data, error, count } = await supabase
        .from('job_tech_tags')
        .select('*', { count: 'exact' })
        .order(sortBy, { ascending: sortOrder === 'asc' })
        .range(from, to)
      if (error) throw error
      return { items: data ?? [], totalCount: count ?? 0 }
    },
  })

  const createJobTechTag = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('job_tech_tags').insert(values)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['job_tech_tags'] }),
  })

  const deleteJobTechTag = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('job_tech_tags').delete().eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['job_tech_tags'] }),
  })

  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null)
  const [createForm, setCreateForm] = useState<Record<string, string | boolean>>({ job_id: '', tech_tag_id: '' })

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Job Tech Tags</h1>
          {!jobTechTags.isPending && (
            <p className="text-sm text-muted-foreground mt-0.5">
              {jobTechTags.data?.totalCount ?? 0} total
            </p>
          )}
        </div>
        <Button onClick={() => setIsCreateOpen(true)} size="sm">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16" className="mr-1.5 -ml-0.5">
            <path d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
          </svg>
          New Job Tech Tag
        </Button>
      </div>



      {/* Create dialog */}
      <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Create Job Tech Tag</DialogTitle>
            <DialogDescription className="sr-only">Fill in the details to create a new Job Tech Tag.</DialogDescription>
          </DialogHeader>
          <form
            className="space-y-4 py-2"
            onSubmit={(e) => {
              e.preventDefault()
              createJobTechTag.mutate(createForm)
              setCreateForm({ job_id: '', tech_tag_id: '' })
              setIsCreateOpen(false)
            }}
          >
            <div>
              <label htmlFor="field-job_id" className="text-sm font-medium">Job Id</label>
              <Input id="field-job_id" type="text" value={String(createForm.job_id ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, job_id: e.target.value }))} placeholder="Enter job id" />
            </div>
            <div>
              <label htmlFor="field-tech_tag_id" className="text-sm font-medium">Tech Tag Id</label>
              <Input id="field-tech_tag_id" type="text" value={String(createForm.tech_tag_id ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, tech_tag_id: e.target.value }))} placeholder="Enter tech tag id" />
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setIsCreateOpen(false)}>Cancel</Button>
              <Button type="submit" disabled={createJobTechTag.isPending}>
                {createJobTechTag.isPending ? 'Creating…' : 'Create'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Delete confirm dialog */}
      <Dialog open={!!deleteTargetId} onOpenChange={(open) => { if (!open) setDeleteTargetId(null) }}>
        <DialogContent className="sm:max-w-sm">
          <DialogHeader>
            <DialogTitle>Delete Job Tech Tag?</DialogTitle>
            <DialogDescription className="sr-only">This action cannot be undone.</DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteTargetId(null)}>Cancel</Button>
            <Button
              variant="destructive"
              disabled={deleteJobTechTag.isPending}
              onClick={() => {
                if (deleteTargetId) {
                  deleteJobTechTag.mutate(deleteTargetId)
                  setDeleteTargetId(null)
                }
              }}
            >
              {deleteJobTechTag.isPending ? 'Deleting…' : 'Delete'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Data table */}
      {jobTechTags.isPending ? (
        <Card>
          <CardContent className="p-0">
            <div className="space-y-0 divide-y">
              {Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="flex items-center gap-4 px-4 py-3.5">
                  <Skeleton className="h-4 w-[40%]" />
                  <Skeleton className="h-4 w-[25%]" />
                  <Skeleton className="h-4 w-[15%] ml-auto" />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      ) : jobTechTags.error ? (
        <Card className="border-destructive/30 bg-destructive/5">
          <CardContent className="py-10 text-center">
            <p className="text-sm text-destructive font-medium">Failed to load data</p>
            <p className="text-xs text-muted-foreground mt-1">{jobTechTags.error.message}</p>
            <Button variant="outline" size="sm" className="mt-4" onClick={() => jobTechTags.refetch()}>
              Try again
            </Button>
          </CardContent>
        </Card>
      ) : (jobTechTags.data?.items ?? []).length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center">
            <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-muted">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5" className="text-muted-foreground">
                <path strokeLinecap="round" strokeLinejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
              </svg>
            </div>
            <p className="font-medium text-sm">No job tech tags yet. Create your first job tech tags!</p>
            <p className="text-xs text-muted-foreground mt-1">Get started by creating your first one.</p>
            <Button size="sm" className="mt-4" onClick={() => setIsCreateOpen(true)}>
              Create Job Tech Tag
            </Button>
          </CardContent>
        </Card>
      ) : (
        <Card className="overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b bg-muted/40">
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'id') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('id'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'id') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('id'); setSortOrder('asc') }
                    }
                  }}>
                Id {sortBy === 'id' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'created_at') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('created_at'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'created_at') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('created_at'); setSortOrder('asc') }
                    }
                  }}>
                Created At {sortBy === 'created_at' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
                  <th className="px-4 py-3 text-right font-medium text-muted-foreground whitespace-nowrap">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {(jobTechTags.data?.items ?? []).map((item) => (
                  <tr key={item.id} className="group hover:bg-muted/30 transition-colors">
              <td className="px-4 py-3 text-sm">{item.id}</td>
              <td className="px-4 py-3 text-sm">{item.created_at ? new Date(item.created_at).toLocaleDateString() : '—'}</td>
                    <td className="px-4 py-3 text-right whitespace-nowrap">
                      <div className="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <Link to="/job-tech-tags/$id" params={{ id: item.id } as any}>
                          <Button variant="ghost" size="sm" className="h-7 px-2 text-xs">View</Button>
                        </Link>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs text-destructive hover:text-destructive hover:bg-destructive/10"
                          onClick={() => setDeleteTargetId(item.id)}
                        >
                          Delete
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      {/* Pagination */}
      {jobTechTags.data && jobTechTags.data.totalCount > pageSize && (
        <div className="flex items-center justify-between py-2">
          <p className="text-xs text-muted-foreground">
            Showing {page * pageSize + 1}–{Math.min((page + 1) * pageSize, jobTechTags.data.totalCount)} of {jobTechTags.data.totalCount}
          </p>
          <div className="flex gap-1">
            <Button variant="outline" size="sm" onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0}>
              ← Prev
            </Button>
            <Button variant="outline" size="sm" onClick={() => setPage(p => p + 1)} disabled={(page + 1) * pageSize >= jobTechTags.data.totalCount}>
              Next →
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
