// Auto-generated by VibeStack — deterministic assembly from PageFeatureSpec
import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

export const Route = createFileRoute('/_authenticated/job-tech-tags/$id')({
  component: JobTechTagDetailPage,
})

function JobTechTagDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const jobTechTags = useQuery({
    queryKey: ['job_tech_tags', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('job_tech_tags').select('*').eq('id', id).single()
      if (error) throw error
      return data
    },
  })
  const updateJobTechTag = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('job_tech_tags').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['job_tech_tags'] }),
  })


  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | boolean>>({})

  if (jobTechTags.isPending) {
    return <div className="flex justify-center py-12"><p className="text-muted-foreground">Loading...</p></div>
  }

  if (jobTechTags.error) {
    return <div className="flex justify-center py-12"><p className="text-destructive">Error: {jobTechTags.error.message}</p></div>
  }

  const data = jobTechTags.data
  if (!data) {
    return <div className="flex justify-center py-12"><p className="text-muted-foreground">Not found</p></div>
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/job-tech-tags" className="text-sm text-muted-foreground hover:text-foreground">
          ← Back to Job Tech Tags
        </Link>
      </div>

      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">{data.id}</h1>
        <Button onClick={() => {
          if (!isEditing) {
            setEditForm({ job_id: data.job_id ?? '', tech_tag_id: data.tech_tag_id ?? '' })
          }
          setIsEditing(!isEditing)
        }}>
          {isEditing ? 'Cancel' : 'Edit'}
        </Button>
      </div>

      {isEditing ? (
        <Card>
          <CardHeader>
            <CardTitle>Edit Job Tech Tag</CardTitle>
          </CardHeader>
          <CardContent>
            <form
              className="space-y-4"
              onSubmit={(e) => {
                e.preventDefault()
                updateJobTechTag.mutate(editForm)
                setIsEditing(false)
              }}
            >
            <div>
              <label htmlFor="field-job_id" className="text-sm font-medium">Job Id</label>
              <Input id="field-job_id" type="text" value={String(editForm.job_id ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, job_id: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-tech_tag_id" className="text-sm font-medium">Tech Tag Id</label>
              <Input id="field-tech_tag_id" type="text" value={String(editForm.tech_tag_id ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, tech_tag_id: e.target.value }))} />
            </div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateJobTechTag.isPending}>
                  {updateJobTechTag.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <>
        <Card>
          <CardHeader>
            <CardTitle>Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground">Job Id</p>
              <p className="font-medium">{data.job_id}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Tech Tag Id</p>
              <p className="font-medium">{data.tech_tag_id}</p>
            </div>
          </CardContent>
        </Card>
        </>
      )}
    </div>
  )
}
