// Auto-generated by VibeStack — deterministic assembly from PageFeatureSpec
import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog'
import { Skeleton } from '@/components/ui/skeleton'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textarea'

export const Route = createFileRoute('/_authenticated/jobs')({
  component: JobListPage,
})

function JobListPage() {
  const [sortBy, setSortBy] = useState('created_at')
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('desc')
  const [filters, setFilters] = useState<Record<string, string | boolean>>({})
  const [page, setPage] = useState(0)
  const pageSize = 20
  const queryClient = useQueryClient()

  const jobs = useQuery({
    queryKey: ['jobs', 'list', page, sortBy, sortOrder],
    queryFn: async () => {
      const from = page * pageSize
      const to = from + pageSize - 1
      const { data, error, count } = await supabase
        .from('jobs')
        .select('*', { count: 'exact' })
        .order(sortBy, { ascending: sortOrder === 'asc' })
        .range(from, to)
      if (error) throw error
      return { items: data ?? [], totalCount: count ?? 0 }
    },
  })

  const createJob = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('jobs').insert(values)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['jobs'] }),
  })

  const deleteJob = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('jobs').delete().eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['jobs'] }),
  })

  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null)
  const [createForm, setCreateForm] = useState<Record<string, string | boolean>>({ title: '', company_name: '', location_type: '', job_type: '', location_text: '', tech_stack: '', salary_min: '', salary_max: '', salary_currency: '', salary_period: '', description: '', apply_url: '', is_active: false })

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Jobs</h1>
          {!jobs.isPending && (
            <p className="text-sm text-muted-foreground mt-0.5">
              {jobs.data?.totalCount ?? 0} total
            </p>
          )}
        </div>
        <Button onClick={() => setIsCreateOpen(true)} size="sm">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16" className="mr-1.5 -ml-0.5">
            <path d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
          </svg>
          New Job
        </Button>
      </div>


      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-wrap gap-4">
          <div>
            <label htmlFor="filter-job_type" className="text-sm font-medium">Job Type</label>
            <select id="filter-job_type" className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={String(filters.jobType ?? '')} onChange={(e) => setFilters(prev => ({ ...prev, jobType: e.target.value }))}>
              <option value="">All</option>
              <option value="full_time">FullTime</option>
              <option value="contract">Contract</option>
              <option value="freelance">Freelance</option>
            </select>
          </div>
          <div className="flex items-center gap-2">
            <input id="filter-is_active" type="checkbox" checked={!!filters.isActive} onChange={(e) => setFilters(prev => ({ ...prev, isActive: e.target.checked }))} />
            <label htmlFor="filter-is_active" className="text-sm font-medium">Is Active</label>
          </div>
          </div>
        </CardContent>
      </Card>


      {/* Create dialog */}
      <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Create Job</DialogTitle>
            <DialogDescription className="sr-only">Fill in the details to create a new Job.</DialogDescription>
          </DialogHeader>
          <form
            className="space-y-4 py-2"
            onSubmit={(e) => {
              e.preventDefault()
              createJob.mutate(createForm)
              setCreateForm({ title: '', company_name: '', location_type: '', job_type: '', location_text: '', tech_stack: '', salary_min: '', salary_max: '', salary_currency: '', salary_period: '', description: '', apply_url: '', is_active: false })
              setIsCreateOpen(false)
            }}
          >
            <div>
              <label htmlFor="field-title" className="text-sm font-medium">Title</label>
              <Input id="field-title" type="text" value={String(createForm.title ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, title: e.target.value }))} placeholder="Enter title" />
            </div>
            <div>
              <label htmlFor="field-company_name" className="text-sm font-medium">Company Name</label>
              <Input id="field-company_name" type="text" value={String(createForm.company_name ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, company_name: e.target.value }))} placeholder="Enter company name" />
            </div>
            <div>
              <label htmlFor="field-location_type" className="text-sm font-medium">Location Type</label>
              <Input id="field-location_type" type="text" value={String(createForm.location_type ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, location_type: e.target.value }))} placeholder="Enter location type" />
            </div>
            <div>
              <label htmlFor="field-job_type" className="text-sm font-medium">Job Type</label>
              <select id="field-job_type" className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={String(createForm.job_type ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, job_type: e.target.value }))}>
                <option value="">Select...</option>
                  <option value="full_time">FullTime</option>
                  <option value="contract">Contract</option>
                  <option value="freelance">Freelance</option>
              </select>
            </div>
            <div>
              <label htmlFor="field-location_text" className="text-sm font-medium">Location Text</label>
              <Input id="field-location_text" type="text" value={String(createForm.location_text ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, location_text: e.target.value }))} placeholder="Enter location text" />
            </div>
            <div>
              <label htmlFor="field-tech_stack" className="text-sm font-medium">Tech Stack</label>
              <Input id="field-tech_stack" type="text" value={String(createForm.tech_stack ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, tech_stack: e.target.value }))} placeholder="Enter tech stack" />
            </div>
            <div>
              <label htmlFor="field-salary_min" className="text-sm font-medium">Salary Min</label>
              <Input id="field-salary_min" type="number" value={String(createForm.salary_min ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, salary_min: e.target.value }))} placeholder="Enter salary min" />
            </div>
            <div>
              <label htmlFor="field-salary_max" className="text-sm font-medium">Salary Max</label>
              <Input id="field-salary_max" type="number" value={String(createForm.salary_max ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, salary_max: e.target.value }))} placeholder="Enter salary max" />
            </div>
            <div>
              <label htmlFor="field-salary_currency" className="text-sm font-medium">Salary Currency</label>
              <Input id="field-salary_currency" type="text" value={String(createForm.salary_currency ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, salary_currency: e.target.value }))} placeholder="Enter salary currency" />
            </div>
            <div>
              <label htmlFor="field-salary_period" className="text-sm font-medium">Salary Period</label>
              <Input id="field-salary_period" type="text" value={String(createForm.salary_period ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, salary_period: e.target.value }))} placeholder="Enter salary period" />
            </div>
            <div>
              <label htmlFor="field-description" className="text-sm font-medium">Description</label>
              <Textarea id="field-description" value={String(createForm.description ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, description: e.target.value }))} placeholder="Enter description" />
            </div>
            <div>
              <label htmlFor="field-apply_url" className="text-sm font-medium">Apply Url</label>
              <Input id="field-apply_url" type="url" value={String(createForm.apply_url ?? '')} onChange={(e) => setCreateForm(prev => ({ ...prev, apply_url: e.target.value }))} placeholder="e.g., https://example.com" />
            </div>
            <div className="flex items-center gap-2">
              <input id="field-is_active" type="checkbox" checked={!!createForm.is_active} onChange={(e) => setCreateForm(prev => ({ ...prev, is_active: e.target.checked }))} />
              <label htmlFor="field-is_active" className="text-sm font-medium">Is Active</label>
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setIsCreateOpen(false)}>Cancel</Button>
              <Button type="submit" disabled={createJob.isPending}>
                {createJob.isPending ? 'Creating…' : 'Create'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Delete confirm dialog */}
      <Dialog open={!!deleteTargetId} onOpenChange={(open) => { if (!open) setDeleteTargetId(null) }}>
        <DialogContent className="sm:max-w-sm">
          <DialogHeader>
            <DialogTitle>Delete Job?</DialogTitle>
            <DialogDescription className="sr-only">This action cannot be undone.</DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteTargetId(null)}>Cancel</Button>
            <Button
              variant="destructive"
              disabled={deleteJob.isPending}
              onClick={() => {
                if (deleteTargetId) {
                  deleteJob.mutate(deleteTargetId)
                  setDeleteTargetId(null)
                }
              }}
            >
              {deleteJob.isPending ? 'Deleting…' : 'Delete'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Data table */}
      {jobs.isPending ? (
        <Card>
          <CardContent className="p-0">
            <div className="space-y-0 divide-y">
              {Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="flex items-center gap-4 px-4 py-3.5">
                  <Skeleton className="h-4 w-[40%]" />
                  <Skeleton className="h-4 w-[25%]" />
                  <Skeleton className="h-4 w-[15%] ml-auto" />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      ) : jobs.error ? (
        <Card className="border-destructive/30 bg-destructive/5">
          <CardContent className="py-10 text-center">
            <p className="text-sm text-destructive font-medium">Failed to load data</p>
            <p className="text-xs text-muted-foreground mt-1">{jobs.error.message}</p>
            <Button variant="outline" size="sm" className="mt-4" onClick={() => jobs.refetch()}>
              Try again
            </Button>
          </CardContent>
        </Card>
      ) : (jobs.data?.items ?? []).length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center">
            <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-muted">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5" className="text-muted-foreground">
                <path strokeLinecap="round" strokeLinejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
              </svg>
            </div>
            <p className="font-medium text-sm">No jobs yet. Create your first jobs!</p>
            <p className="text-xs text-muted-foreground mt-1">Get started by creating your first one.</p>
            <Button size="sm" className="mt-4" onClick={() => setIsCreateOpen(true)}>
              Create Job
            </Button>
          </CardContent>
        </Card>
      ) : (
        <Card className="overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b bg-muted/40">
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'title') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('title'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'title') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('title'); setSortOrder('asc') }
                    }
                  }}>
                Title {sortBy === 'title' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'location_type') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('location_type'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'location_type') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('location_type'); setSortOrder('asc') }
                    }
                  }}>
                Location Type {sortBy === 'location_type' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'job_type') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('job_type'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'job_type') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('job_type'); setSortOrder('asc') }
                    }
                  }}>
                Job Type {sortBy === 'job_type' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'is_active') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('is_active'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'is_active') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('is_active'); setSortOrder('asc') }
                    }
                  }}>
                Is Active {sortBy === 'is_active' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'salary_min') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('salary_min'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'salary_min') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('salary_min'); setSortOrder('asc') }
                    }
                  }}>
                Salary Min {sortBy === 'salary_min' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
                  tabIndex={0}
                  onClick={() => {
                    if (sortBy === 'salary_max') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                    else { setSortBy('salary_max'); setSortOrder('asc') }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      if (sortBy === 'salary_max') setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
                      else { setSortBy('salary_max'); setSortOrder('asc') }
                    }
                  }}>
                Salary Max {sortBy === 'salary_max' ? (sortOrder === 'asc' ? '↑' : '↓') : ''}
              </th>
                  <th className="px-4 py-3 text-right font-medium text-muted-foreground whitespace-nowrap">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {(jobs.data?.items ?? []).map((item) => (
                  <tr key={item.id} className="group hover:bg-muted/30 transition-colors">
              <td className="px-4 py-3 text-sm">{item.title}</td>
              <td className="px-4 py-3 text-sm">{item.location_type}</td>
              <td className="px-4 py-3 text-sm"><Badge variant="secondary">{item.job_type}</Badge></td>
              <td className="px-4 py-3 text-sm"><Badge variant={item.is_active ? 'default' : 'outline'}>{item.is_active ? 'Yes' : 'No'}</Badge></td>
              <td className="px-4 py-3 text-sm">{item.salary_min}</td>
              <td className="px-4 py-3 text-sm">{item.salary_max}</td>
                    <td className="px-4 py-3 text-right whitespace-nowrap">
                      <div className="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <Link to="/jobs/$id" params={{ id: item.id } as any}>
                          <Button variant="ghost" size="sm" className="h-7 px-2 text-xs">View</Button>
                        </Link>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs text-destructive hover:text-destructive hover:bg-destructive/10"
                          onClick={() => setDeleteTargetId(item.id)}
                        >
                          Delete
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      {/* Pagination */}
      {jobs.data && jobs.data.totalCount > pageSize && (
        <div className="flex items-center justify-between py-2">
          <p className="text-xs text-muted-foreground">
            Showing {page * pageSize + 1}–{Math.min((page + 1) * pageSize, jobs.data.totalCount)} of {jobs.data.totalCount}
          </p>
          <div className="flex gap-1">
            <Button variant="outline" size="sm" onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0}>
              ← Prev
            </Button>
            <Button variant="outline" size="sm" onClick={() => setPage(p => p + 1)} disabled={(page + 1) * pageSize >= jobs.data.totalCount}>
              Next →
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
