// Auto-generated by VibeStack — deterministic assembly from PageFeatureSpec
import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textarea'

export const Route = createFileRoute('/_authenticated/jobs/$id')({
  component: JobDetailPage,
})

function JobDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const jobs = useQuery({
    queryKey: ['jobs', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('jobs').select('*').eq('id', id).single()
      if (error) throw error
      return data
    },
  })
  const updateJob = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('jobs').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['jobs'] }),
  })


  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | boolean>>({})

  if (jobs.isPending) {
    return <div className="flex justify-center py-12"><p className="text-muted-foreground">Loading...</p></div>
  }

  if (jobs.error) {
    return <div className="flex justify-center py-12"><p className="text-destructive">Error: {jobs.error.message}</p></div>
  }

  const data = jobs.data
  if (!data) {
    return <div className="flex justify-center py-12"><p className="text-muted-foreground">Not found</p></div>
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/jobs" className="text-sm text-muted-foreground hover:text-foreground">
          ← Back to Jobs
        </Link>
      </div>

      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">{data.title}</h1>
        <Button onClick={() => {
          if (!isEditing) {
            setEditForm({ title: data.title ?? '', company_name: data.company_name ?? '', location_type: data.location_type ?? '', job_type: data.job_type ?? '', location_text: data.location_text ?? '', tech_stack: data.tech_stack ?? '', salary_min: data.salary_min ?? '', salary_max: data.salary_max ?? '', salary_currency: data.salary_currency ?? '', salary_period: data.salary_period ?? '', description: data.description ?? '', apply_url: data.apply_url ?? '', is_active: data.is_active ?? '' })
          }
          setIsEditing(!isEditing)
        }}>
          {isEditing ? 'Cancel' : 'Edit'}
        </Button>
      </div>

      {isEditing ? (
        <Card>
          <CardHeader>
            <CardTitle>Edit Job</CardTitle>
          </CardHeader>
          <CardContent>
            <form
              className="space-y-4"
              onSubmit={(e) => {
                e.preventDefault()
                updateJob.mutate(editForm)
                setIsEditing(false)
              }}
            >
            <div>
              <label htmlFor="field-title" className="text-sm font-medium">Title</label>
              <Input id="field-title" type="text" value={String(editForm.title ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, title: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-company_name" className="text-sm font-medium">Company Name</label>
              <Input id="field-company_name" type="text" value={String(editForm.company_name ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, company_name: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-location_type" className="text-sm font-medium">Location Type</label>
              <Input id="field-location_type" type="text" value={String(editForm.location_type ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, location_type: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-job_type" className="text-sm font-medium">Job Type</label>
              <select id="field-job_type" className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={String(editForm.job_type ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, job_type: e.target.value }))}>
                <option value="">Select...</option>

              </select>
            </div>
            <div>
              <label htmlFor="field-location_text" className="text-sm font-medium">Location Text</label>
              <Input id="field-location_text" type="text" value={String(editForm.location_text ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, location_text: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-tech_stack" className="text-sm font-medium">Tech Stack</label>
              <Input id="field-tech_stack" type="text" value={String(editForm.tech_stack ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, tech_stack: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-salary_min" className="text-sm font-medium">Salary Min</label>
              <Input id="field-salary_min" type="number" value={String(editForm.salary_min ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, salary_min: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-salary_max" className="text-sm font-medium">Salary Max</label>
              <Input id="field-salary_max" type="number" value={String(editForm.salary_max ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, salary_max: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-salary_currency" className="text-sm font-medium">Salary Currency</label>
              <Input id="field-salary_currency" type="text" value={String(editForm.salary_currency ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, salary_currency: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-salary_period" className="text-sm font-medium">Salary Period</label>
              <Input id="field-salary_period" type="text" value={String(editForm.salary_period ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, salary_period: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-description" className="text-sm font-medium">Description</label>
              <Textarea id="field-description" value={String(editForm.description ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, description: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-apply_url" className="text-sm font-medium">Apply Url</label>
              <Input id="field-apply_url" type="url" value={String(editForm.apply_url ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, apply_url: e.target.value }))} />
            </div>
            <div className="flex items-center gap-2">
              <input id="field-is_active" type="checkbox" checked={!!editForm.is_active} onChange={(e) => setEditForm(prev => ({ ...prev, is_active: e.target.checked }))} />
              <label htmlFor="field-is_active" className="text-sm font-medium">Is Active</label>
            </div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateJob.isPending}>
                  {updateJob.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <>
        <Card>
          <CardHeader>
            <CardTitle>Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground">Title</p>
              <p className="font-medium">{data.title}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Company Name</p>
              <p className="font-medium">{data.company_name}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Location Text</p>
              <p className="font-medium">{data.location_text}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Tech Stack</p>
              <p className="font-medium">{data.tech_stack}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Salary Currency</p>
              <p className="font-medium">{data.salary_currency}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Salary Period</p>
              <p className="font-medium">{data.salary_period}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Description</p>
              <p className="font-medium">{data.description}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Apply Url</p>
              <p className="font-medium"><a href={data.apply_url} target="_blank" rel="noopener noreferrer" className="text-primary underline">{data.apply_url}</a></p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Properties</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground">Location Type</p>
              <p className="font-medium">{data.location_type}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Job Type</p>
              <p className="font-medium"><Badge variant="secondary">{data.job_type}</Badge></p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Salary Min</p>
              <p className="font-medium">{data.salary_min}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Salary Max</p>
              <p className="font-medium">{data.salary_max}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Is Active</p>
              <p className="font-medium"><Badge variant={data.is_active ? 'default' : 'outline'}>{data.is_active ? 'Yes' : 'No'}</Badge></p>
            </div>
          </CardContent>
        </Card>
        </>
      )}
    </div>
  )
}
