// Auto-generated by VibeStack — deterministic assembly from PageFeatureSpec
import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

export const Route = createFileRoute('/_authenticated/tech-tags/$id')({
  component: TechTagDetailPage,
})

function TechTagDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const techTags = useQuery({
    queryKey: ['tech_tags', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('tech_tags').select('*').eq('id', id).single()
      if (error) throw error
      return data
    },
  })
  const updateTechTag = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('tech_tags').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['tech_tags'] }),
  })


  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | boolean>>({})

  if (techTags.isPending) {
    return <div className="flex justify-center py-12"><p className="text-muted-foreground">Loading...</p></div>
  }

  if (techTags.error) {
    return <div className="flex justify-center py-12"><p className="text-destructive">Error: {techTags.error.message}</p></div>
  }

  const data = techTags.data
  if (!data) {
    return <div className="flex justify-center py-12"><p className="text-muted-foreground">Not found</p></div>
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/tech-tags" className="text-sm text-muted-foreground hover:text-foreground">
          ← Back to Tech Tags
        </Link>
      </div>

      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">{data.name}</h1>
        <Button onClick={() => {
          if (!isEditing) {
            setEditForm({ name: data.name ?? '', slug: data.slug ?? '' })
          }
          setIsEditing(!isEditing)
        }}>
          {isEditing ? 'Cancel' : 'Edit'}
        </Button>
      </div>

      {isEditing ? (
        <Card>
          <CardHeader>
            <CardTitle>Edit Tech Tag</CardTitle>
          </CardHeader>
          <CardContent>
            <form
              className="space-y-4"
              onSubmit={(e) => {
                e.preventDefault()
                updateTechTag.mutate(editForm)
                setIsEditing(false)
              }}
            >
            <div>
              <label htmlFor="field-name" className="text-sm font-medium">Name</label>
              <Input id="field-name" type="text" value={String(editForm.name ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, name: e.target.value }))} />
            </div>
            <div>
              <label htmlFor="field-slug" className="text-sm font-medium">Slug</label>
              <Input id="field-slug" type="text" value={String(editForm.slug ?? '')} onChange={(e) => setEditForm(prev => ({ ...prev, slug: e.target.value }))} />
            </div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateTechTag.isPending}>
                  {updateTechTag.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <>
        <Card>
          <CardHeader>
            <CardTitle>Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground">Name</p>
              <p className="font-medium">{data.name}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Slug</p>
              <p className="font-medium">{data.slug}</p>
            </div>
          </CardContent>
        </Card>
        </>
      )}
    </div>
  )
}
