/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by VibeStack — do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedImport } from './routes/_authenticated/route'
import { Route as JobsListImport } from './routes/_authenticated/jobs'
import { Route as JobsDetailImport } from './routes/_authenticated/jobs.$id'
import { Route as TechTagsListImport } from './routes/_authenticated/tech-tags'
import { Route as TechTagsDetailImport } from './routes/_authenticated/tech-tags.$id'

const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)
const AuthenticatedRoute = AuthenticatedImport.update({ id: '/_authenticated', getParentRoute: () => rootRoute } as any)

const JobsListRoute = JobsListImport.update({ path: '/jobs', getParentRoute: () => AuthenticatedRoute } as any)
const JobsDetailRoute = JobsDetailImport.update({ path: '/jobs/$id', getParentRoute: () => AuthenticatedRoute } as any)
const TechTagsListRoute = TechTagsListImport.update({ path: '/tech-tags', getParentRoute: () => AuthenticatedRoute } as any)
const TechTagsDetailRoute = TechTagsDetailImport.update({ path: '/tech-tags/$id', getParentRoute: () => AuthenticatedRoute } as any)

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute.addChildren([
    JobsListRoute,
    JobsDetailRoute,
    TechTagsListRoute,
    TechTagsDetailRoute,
  ]),
])
